"""initial schema

Revision ID: ed052bd41e79
Revises:
Create Date: 2026-06-09 17:26:24.449434

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ed052bd41e79"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webhook_subscriptions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "url",
            sa.String(length=2048),
            nullable=False,
            comment="URL для отправки webhook-уведомлений",
        ),
        sa.Column(
            "events",
            postgresql.ARRAY(sa.String()),
            nullable=False,
            comment="Список событий: batch_created, batch_closed, product_aggregated и т.д.",
        ),
        sa.Column(
            "secret_key",
            sa.String(length=512),
            nullable=False,
            comment="Секретный ключ для HMAC-подписи тела запроса",
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="Активна ли подписка"
        ),
        sa.Column(
            "retry_count",
            sa.Integer(),
            nullable=False,
            comment="Количество попыток повторной отправки при неудаче",
        ),
        sa.Column(
            "timeout",
            sa.Integer(),
            nullable=False,
            comment="Таймаут запроса в секундах",
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "work_centers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "identifier",
            sa.String(length=100),
            nullable=False,
            comment="Идентификатор РЦ из внешней системы (например, RC-001)",
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Название рабочего центра",
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_work_centers_identifier"), "work_centers", ["identifier"], unique=True
    )
    op.create_table(
        "batches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "is_closed", sa.Boolean(), nullable=False, comment="Признак закрытия партии"
        ),
        sa.Column(
            "closed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата и время закрытия партии",
        ),
        sa.Column(
            "task_description",
            sa.Text(),
            nullable=False,
            comment="Представление задания на смену (текстовое описание)",
        ),
        sa.Column(
            "work_center_id",
            sa.Integer(),
            nullable=False,
            comment="FK на рабочий центр",
        ),
        sa.Column(
            "shift",
            sa.String(length=50),
            nullable=False,
            comment="Номер/название смены (например, '1 смена')",
        ),
        sa.Column(
            "team", sa.String(length=255), nullable=False, comment="Название бригады"
        ),
        sa.Column(
            "batch_number",
            sa.Integer(),
            nullable=False,
            comment="Номер партии из внешней системы",
        ),
        sa.Column("batch_date", sa.Date(), nullable=False, comment="Дата партии"),
        sa.Column(
            "nomenclature",
            sa.String(length=500),
            nullable=False,
            comment="Наименование номенклатуры",
        ),
        sa.Column(
            "ekn_code",
            sa.String(length=100),
            nullable=False,
            comment="Код ЕКН (единый классификатор номенклатуры)",
        ),
        sa.Column(
            "shift_start",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата и время начала смены",
        ),
        sa.Column(
            "shift_end",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата и время окончания смены",
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["work_center_id"], ["work_centers.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("batch_number", "batch_date", name="uq_batch_number_date"),
    )
    op.create_index("idx_batch_closed", "batches", ["is_closed"], unique=False)
    op.create_index(
        "idx_batch_shift_times", "batches", ["shift_start", "shift_end"], unique=False
    )
    op.create_index(
        op.f("ix_batches_batch_date"), "batches", ["batch_date"], unique=False
    )
    op.create_index(
        op.f("ix_batches_batch_number"), "batches", ["batch_number"], unique=False
    )
    op.create_index(
        op.f("ix_batches_work_center_id"), "batches", ["work_center_id"], unique=False
    )
    op.create_table(
        "webhook_deliveries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "subscription_id", sa.Integer(), nullable=False, comment="FK на подписку"
        ),
        sa.Column(
            "event_type",
            sa.String(length=100),
            nullable=False,
            comment="Тип события (batch_created, batch_closed и т.д.)",
        ),
        sa.Column(
            "payload",
            sa.JSON(),
            nullable=False,
            comment="Тело отправленного запроса (JSON)",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="Статус доставки: pending, success, failed",
        ),
        sa.Column(
            "attempts",
            sa.Integer(),
            nullable=False,
            comment="Количество выполненных попыток отправки",
        ),
        sa.Column(
            "response_status",
            sa.Integer(),
            nullable=True,
            comment="HTTP-статус ответа внешнего сервера",
        ),
        sa.Column(
            "response_body",
            sa.Text(),
            nullable=True,
            comment="Тело ответа внешнего сервера (первые N символов)",
        ),
        sa.Column(
            "error_message",
            sa.Text(),
            nullable=True,
            comment="Текст ошибки при неудачной доставке",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата и время создания записи о доставке",
        ),
        sa.Column(
            "delivered_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата и время успешной доставки",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"], ["webhook_subscriptions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_webhook_deliveries_event_type"),
        "webhook_deliveries",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webhook_deliveries_subscription_id"),
        "webhook_deliveries",
        ["subscription_id"],
        unique=False,
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "unique_code",
            sa.String(length=255),
            nullable=False,
            comment="Уникальный код продукции (штрих-код / QR-код)",
        ),
        sa.Column("batch_id", sa.Integer(), nullable=False, comment="FK на партию"),
        sa.Column(
            "is_aggregated",
            sa.Boolean(),
            nullable=False,
            comment="Признак агрегации (продукция прошла контроль)",
        ),
        sa.Column(
            "aggregated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата и время агрегации",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата и время создания записи",
        ),
        sa.ForeignKeyConstraint(["batch_id"], ["batches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_product_batch_aggregated",
        "products",
        ["batch_id", "is_aggregated"],
        unique=False,
    )
    op.create_index(
        op.f("ix_products_batch_id"), "products", ["batch_id"], unique=False
    )
    op.create_index(
        op.f("ix_products_is_aggregated"), "products", ["is_aggregated"], unique=False
    )
    op.create_index(
        op.f("ix_products_unique_code"), "products", ["unique_code"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_unique_code"), table_name="products")
    op.drop_index(op.f("ix_products_is_aggregated"), table_name="products")
    op.drop_index(op.f("ix_products_batch_id"), table_name="products")
    op.drop_index("idx_product_batch_aggregated", table_name="products")
    op.drop_table("products")
    op.drop_index(
        op.f("ix_webhook_deliveries_subscription_id"), table_name="webhook_deliveries"
    )
    op.drop_index(
        op.f("ix_webhook_deliveries_event_type"), table_name="webhook_deliveries"
    )
    op.drop_table("webhook_deliveries")
    op.drop_index(op.f("ix_batches_work_center_id"), table_name="batches")
    op.drop_index(op.f("ix_batches_batch_number"), table_name="batches")
    op.drop_index(op.f("ix_batches_batch_date"), table_name="batches")
    op.drop_index("idx_batch_shift_times", table_name="batches")
    op.drop_index("idx_batch_closed", table_name="batches")
    op.drop_table("batches")
    op.drop_index(op.f("ix_work_centers_identifier"), table_name="work_centers")
    op.drop_table("work_centers")
    op.drop_table("webhook_subscriptions")
    # ### end Alembic commands ###
